In [200]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import pandas as pd
import cv2 as cv
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.utils import to_categorical

In [201]:
mnist_train = pd.read_csv(r"train_digit_recognition.csv")
mnist_test = pd.read_csv(r"test_digit_recognition.csv")


In [202]:
print(mnist_train.head())

   label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  pixel9  pixel10  pixel11  pixel12  pixel13  pixel14  pixel15  \
0       0       0        0        0        0        0        0        0   
1       0       0        0        0        0        0        0        0   
2       0       0        0        0        0        0        0        0   
3       0       0        0        0        0        0        0        0   
4       0       0        0        0        0        0        0        0   

   pixel16  pixel17  pixel18  pixel19  pixel20  pixel21  pixel22  pixel23  \
0        0     

In [203]:
X_train=mnist_train.drop(['label'], axis=1) #df= df.drop(['Date'], axis=1)
y_train=mnist_train['label']

X_test=(mnist_test)


In [204]:

print(X_train.shape)


(42000, 784)


In [205]:
train_images = X_train.to_numpy()
test_images=X_test.to_numpy()

print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)


(42000, 784)
(42000,)
(28000, 784)


In [206]:
print((train_labels))


[1 0 1 ... 7 6 9]


In [207]:
train_images = train_images.reshape((42000, 28, 28))
test_images = test_images.reshape((28000, 28, 28))
#train_labels=y_train.values.tolist()
#train_labels=np.array(train_labels)

print(train_images.shape)
print(test_images.shape)
print(train_labels.shape)


(42000, 28, 28)
(28000, 28, 28)
(42000,)


In [208]:
print(train_labels)

[1 0 1 ... 7 6 9]


In [209]:
#pd.set_option('display.max_columns', None)
#print(X_train.head())

In [210]:
# Normalize the train dataset
train_images = tf.keras.utils.normalize(train_images, axis=1)
# Normalize the test dataset
test_images = tf.keras.utils.normalize(test_images, axis=1)
#to categorical
#train_labels=train_labels.reshape((42000,10,2))
#train_labels = to_categorical(train_labels) 
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)

(42000, 28, 28)
(42000,)
(28000, 28, 28)


In [211]:
print(train_labels)

[1 0 1 ... 7 6 9]


In [212]:
#Build the model object
model = tf.keras.models.Sequential()
# Add the Flatten Layer
model.add(tf.keras.layers.Flatten())
# Build the input and the hidden layers
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
# Build the output layer
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))

In [213]:
model.compile(loss='sparse_categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
# Compile the model
#model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.fit(x=train_images, y=train_labels, epochs=15)

# Evaluate the model performance
#test_loss, test_acc = model.evaluate(x=X_test, y=y_test)


Epoch 1/15
1313/1313 [==============================] - 120s 6ms/step - loss: 0.3113 - accuracy: 0.9110
Epoch 2/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.1281 - accuracy: 0.9612
Epoch 3/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.0855 - accuracy: 0.9733
Epoch 4/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.0613 - accuracy: 0.9810
Epoch 5/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.0466 - accuracy: 0.9848
Epoch 6/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.0335 - accuracy: 0.9895
Epoch 7/15
1313/1313 [==============================] - 8s 6ms/step - loss: 0.0272 - accuracy: 0.9906
Epoch 8/15
1313/1313 [==============================] - 7s 5ms/step - loss: 0.0213 - accuracy: 0.9926
Epoch 9/15
1313/1313 [==============================] - 7s 6ms/step - loss: 0.0170 - accuracy: 0.9943: 0s - loss: 0.0163 - accuracy: 
Epoch 10/15
1313/1313 [=========================

In [214]:

predictions = model.predict([test_images]) # Make prediction
for i in range(10):
    print(np.argmax(predictions[i]))  # Print out the number

Consider rewriting this model with the Functional API.
2
0
9
9
3
7
0
3
0
3


In [215]:
#--------SUBMISSION------------
predictions = np.argmax(predictions, axis=1)
print(predictions.shape)

(28000,)


In [216]:
image_id =list(range(1, 28001))
submit = pd.DataFrame()
submit['ImageId'] = image_id
submit['Label']=predictions
submit.to_csv('submit_digit_recognizer.csv', index=False)